import pandas as pd
import base64
import requests

# TODO: OpenAI KEY
api_key = "Paste your API key here!"

system_message = '''You are a very wise architecture professor. Your task is to study the data I provide which consists of the following points:
    - Image of an architectural project
    - Location of this architectural project
    - Topics belonging to this project which is generated by another AI model based on all the common topics found in thousands of these types of projects'''

user_message = "Here are the data points for this architectural project. After studying it, I would like you to generate me a short but very comprehensive caption for this image which I will be using as an input to a generative AI model. Please try to keep the caption's length in 20-30 words and put more weight on the specifics of the image."

def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')
    
def create_and_send_request(image_path: str, location: str, description: str, topics: str) -> str:
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    base64_image = encode_image(image_path)

    payload = {
        "model": "gpt-4-vision-preview",
        "messages": [
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": system_message
                    }
                ]
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": user_message
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{base64_image}",
                            "detail": "low"
                        }
                    },
                    {
                        "type": "text",
                        "text": f"Location: {location}"
                    },
                    {
                        "type": "text",
                        "text": f"Topics: {topics}"
                    }
                ]
            }
        ],
        "max_tokens": 300
    }

    response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload)
    response_json = response.json()

    return response_json["choices"][0]["message"]["content"]

with open('./output/ExteriorImages.xlsx', 'rb') as data_file:
    data = pd.read_excel(data_file, header=None)
    for index, row in data.iterrows():
        id, location, description, topics, image_path = row[0], row[1], row[2], row[3], row[4]
        if image_path == "./output/Exterior/image_9251.png":
            response = create_and_send_request(image_path, location, description, topics)
            print(response)
            break